name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      # Maven version 3.9.4 is not currently supported by the GluonFX Maven Plugin
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.8

      # Make sure the latest GraalVM is installed.
      # after this step env.JAVA_HOME and env.GRAALVM_HOME will point to the GraalVM location
      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        # set GITHUB_TOKEN to avoid exceeding GitHub's API rate limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a staging directory where the binary will be copied into
      - name: Make staging directory
        run: mkdir staging

      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}
      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
      - name: Show created files
        run: ls -l target/gluonfx/x86_64-darwin/
      - name: Copy native app to staging
        run: cp -r target/gluonfx/x86_64-darwin/Emoji* staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

