name: Linux JAR and Native

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v2

      # Make sure the latest GraalVM is installed.
      # after this step env.JAVA_HOME and env.GRAALVM_HOME will point to the GraalVM location
      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        # set GITHUB_TOKEN to avoid exceeding GitHub's API rate limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install extra required packaged on top of ubuntu-latest
      - name: Install libraries
        run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      # Create a staging directory where the binary will be copied into
      - name: Make staging directory
        run: mkdir staging

      - name: Build JAR with Maven
        run: mvn -B package
      - name: Copy JAR to staging
        run: cp target/*.jar staging
      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}
      - name: Gluon Build
        run: mvn -DconsoleProcessLog=true -Pdesktop gluonfx:build gluonfx:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
      - name: Show created files
        run: ls -l target/gluonfx/x86_64-linux/
      - name: Copy native app to staging
        run: cp -r target/gluonfx/x86_64-linux/EmojiSnakeGameApp staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
